---
resources:
- name: msglib-cpp-git
  type: git
  icon: github
  source:
    uri: http://fir.love.io:3000/ChrisLove/msglib-cpp

jobs:
- name: set-pipeline
  public: true
  plan:
  - get: msglib-cpp-git
    trigger: true
  - set_pipeline: msglib-cpp
    file: msglib-cpp-git/ci/pipeline.yml
- name: build-matrix
  public: true
  plan:  
  - get: msglib-cpp-git
    trigger: true
    passed: 
    - set-pipeline
  - in_parallel:
    - task: gcc11_1_1
      file: msglib-cpp-git/ci/gcc1111.yml
    - task: gcc10_3_0
      file: msglib-cpp-git/ci/gcc1030.yml
    - task: gcc9_4_0
      file: msglib-cpp-git/ci/gcc940.yml
    - task: gcc8_4_0
      file: msglib-cpp-git/ci/gcc840.yml

- name: sanitizers
  public: true
  plan:
  - get: msglib-cpp-git
    trigger: true
    passed: 
    - build-matrix
  - in_parallel:
    - task: asan
      file: msglib-cpp-git/ci/asan.yml
    - task: tsan
      file: msglib-cpp-git/ci/tsan.yml

        