---
resources:
- name: msglib-cpp-git
  type: git
  icon: github
  source:
    uri: http://fir.love.io:3000/CJLove/msglib-cpp

jobs:
- name: set-pipeline
  public: true
  plan:
  - get: msglib-cpp-git
    trigger: true
  - set_pipeline: msglib-cpp
    file: msglib-cpp-git/ci/pipeline.yml

# Build using current gcc and clang and fail fast
- name: build-current
  public: true
  plan:
  - get: msglib-cpp-git
    passed: [ set-pipeline ]
    trigger: true
  - in_parallel:
    - task: gcc1311
      file: msglib-cpp-git/ci/gcc1311.yml
    - task: clang
      file: msglib-cpp-git/ci/clang.yml


- name: build-matrix
  public: true
  plan:  
  - get: msglib-cpp-git
    passed: [ build-current ]
    trigger: true
  - in_parallel:
    - task: gcc12_3_0
      file: msglib-cpp-git/ci/gcc1230.yml
    - task: gcc11_3_0
      file: msglib-cpp-git/ci/gcc1130.yml
    - task: gcc10_3_0
      file: msglib-cpp-git/ci/gcc1030.yml
    - task: gcc9_4_0
      file: msglib-cpp-git/ci/gcc940.yml

- name: sanitizers
  public: true
  plan:
  - get: msglib-cpp-git
    passed: [ build-matrix ]
    trigger: true
  - in_parallel:
    - task: asan
      privileged: true
      file: msglib-cpp-git/ci/asan.yml
    - task: tsan
      file: msglib-cpp-git/ci/tsan.yml

        
