name: ci

on: [push, pull_request]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        config:
          - { compiler: gcc, version: 9, build_type: Release, cppstd: 17, examples: OFF }
          - { compiler: gcc, version: 10, build_type: Debug, cppstd: 20, examples: ON }
          - { compiler: gcc, version: 11, build_type: Debug, cppstd: 20, examples: OFF }
          - { compiler: gcc, version: 12, build_type: Release, cppstd: 20, examples: ON }
#          - { compiler: clang, version: 15, build_type: Debug, cppstd: 17, examples: OFF }
#          - { compiler: clang, version: 15, build_type: Release, cppstd: 20, examples: ON }
    container:
      image: ${{ matrix.config.compiler == 'clang' && 'teeks99/clang-ubuntu' || matrix.config.compiler }}:${{ matrix.config.version }}
    name: "${{ matrix.config.compiler}} ${{ matrix.config.version }} (C++${{ matrix.config.cppstd }}, ${{ matrix.config.build_type }})"
    steps:
      - uses: actions/checkout@main
      - name: Setup
        run: |
          apt-get update && apt-get install -y curl git
          CMAKE_VERSION="3.24.2"
          curl -sSL https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-linux-x86_64.sh -o install-cmake.sh
          chmod +x install-cmake.sh
          ./install-cmake.sh --prefix=/usr/local --skip-license
      - name: Setup Compiler
        if: matrix.config.compiler == 'clang'
        run: |
          if [[ "${{ matrix.config.version }}" -ge 4 ]]; then
            scripts/ci_setup_clang.sh "${{ matrix.config.version }}"
            echo "CXXFLAGS=-stdlib=libc++" >> $GITHUB_ENV
          fi
          echo "CC=clang-${{ matrix.config.version }}" >> $GITHUB_ENV
          echo "CXX=clang++-${{ matrix.config.version }}" >> $GITHUB_ENV
      - name: Dependencies
        run: |
          # install fmtlib
          curl -sSL https://github.com/fmtlib/fmt/archive/refs/tags/9.1.0.tar.gz -o /tmp/fmtlib.tar.gz
          tar zxf /tmp/fmtlib.tar.gz
          pushd fmt* && mkdir build && cd build && cmake -DFMG_TEST=OFF -DCMAKE_BUILD_TYPE=Release .. && make install && popd
          
          # install spdlog
          curl -sSL https://github.com/gabime/spdlog/archive/refs/tags/v1.11.0.tar.gz -o /tmp/spdlog.tar.gz
          tar zxf /tmp/spdlog.tar.gz
          pushd spdlog* && mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release .. && make install && popd

          # Install googletest
          curl -sSL https://github.com/google/googletest/archive/refs/tags/v1.13.0.tar.gz -o /tmp/googletest.tar.gz
          tar zxf /tmp/googletest.tar.gz
          pushd googletest-* && mkdir build && cd build && cmake .. && make install && popd
          
      - name: Build
        run: |
          mkdir -p build && cd build
          export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
          cmake .. \
            -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} \
            -DCMAKE_CXX_STANDARD=${{ matrix.config.cppstd }} \
            -DBUILD_EXAMPLES=${{ matrix.config.example }} \
            -DBUILD_TESTS=ON 
          make -j2
          ctest -j2 --output-on-failure